apiVersion: v1
kind: Service
metadata:
  name: verivue-backend-service
spec:
  type: LoadBalancer
  selector:
    app: verivue-backend
  ports:
  - protocol: TCP
    port: 5000        # External port users will connect to
    targetPort: 5000   # Internal port of the Flask app
